const courses = [
  {
    id: 1,
    name: 'Curso C',
    detail: 'Programación en C de Cero a Experto',
    cost: 1599.0,
    hours: 45,
    img: 'img/courses/course01.jpeg',
    link: 'detail01.html',
    date: new Date(2023, 5, 9),
  },
  {
    id: 2,
    name: 'JavaScript',
    detail: 'Master en programación fullstack JavaScript Angular Node',
    cost: 1799.0,
    hours: 28,
    img: 'img/courses/course02.jpeg',
    link: 'detail02.html',
    date: new Date(2023, 5, 14),
  },
  {
    id: 3,
    name: 'POO',
    detail: 'Programación Orientada a Objetos',
    cost: 1199.0,
    hours: 5,
    img: 'img/courses/course03.jpeg',
    link: 'detail03.html',
    date: new Date(2023, 5, 23),
  },
  {
    id: 4,
    name: 'Python 3',
    detail: 'Programación de Principiante a Avanzado',
    cost: 1999.0,
    hours: 15,
    img: 'img/courses/course04.jpeg',
    link: 'detail04.html',
    date: new Date(2023, 6, 3),
  },
  {
    id: 5,
    name: 'JAVA',
    detail: 'Aprender a programar con Java',
    cost: 1599.0,
    hours: 30,
    img: 'img/courses/course05.jpeg',
    link: 'detail05.html',
    date: new Date(2023, 6, 6),
  },
  {
    id: 6,
    name: 'Arduino',
    detail: 'Electrónica y programación C desde cero',
    cost: 1550.0,
    hours: 13,
    img: 'img/courses/course06.jpeg',
    link: 'detail06.html',
    date: new Date(2023, 6, 20),
  },
];
